@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Wed Nov 05 16:51:14 +0900 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -L axi_vip_v1_1_11 -L xilinx_vip -i C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include -L axi_vip_v1_1_11 -L xilinx_vip -prj sa_matmul_tb_vlog.prj"
call xvlog  --incr --relax -L uvm -L axi_vip_v1_1_11 -L xilinx_vip -i C:/Xilinx/Vivado/2021.2/data/xilinx_vip/include -L axi_vip_v1_1_11 -L xilinx_vip -prj sa_matmul_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
