@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 08 22:36:05 +0900 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sa_matmul_tb_behav -key {Behavioral:sim_1:Functional:sa_matmul_tb} -tclbatch sa_matmul_tb.tcl -protoinst "protoinst_files/sa_engine_ip_v1_0_bfm_1.protoinst" -view C:/Users/User/Desktop/git/cau-capstone/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_engine_ip_v1_0_tb_behav.wcfg -log simulate.log"
call xsim  sa_matmul_tb_behav -key {Behavioral:sim_1:Functional:sa_matmul_tb} -tclbatch sa_matmul_tb.tcl -protoinst "protoinst_files/sa_engine_ip_v1_0_bfm_1.protoinst" -view C:/Users/User/Desktop/git/cau-capstone/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_engine_ip_v1_0_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
