@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 07 22:14:31 +0900 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_tile_loader_behav -key {Behavioral:sim_1:Functional:tb_tile_loader} -tclbatch tb_tile_loader.tcl -view C:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/unit_tests/unit_tests.waveform/tb_axi_addr_gen_behav.wcfg -view C:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/unit_tests/unit_tests.waveform/tb_bram_pingpong_behav.wcfg -log simulate.log"
call xsim  tb_tile_loader_behav -key {Behavioral:sim_1:Functional:tb_tile_loader} -tclbatch tb_tile_loader.tcl -view C:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/unit_tests/unit_tests.waveform/tb_axi_addr_gen_behav.wcfg -view C:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/unit_tests/unit_tests.waveform/tb_bram_pingpong_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
