# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sa_engine_ip_v1_0_bfm_1/sa_engine_ip_v1_0_bfm_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sa_engine_ip_v1_0_bfm_1 || ORIG_REF_NAME==sa_engine_ip_v1_0_bfm_1} -quiet] -quiet

# IP: bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_slave_0_0/sa_engine_ip_v1_0_bfm_1_slave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sa_engine_ip_v1_0_bfm_1_slave_0_0 || ORIG_REF_NAME==sa_engine_ip_v1_0_bfm_1_slave_0_0} -quiet] -quiet

# IP: bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_master_0_0/sa_engine_ip_v1_0_bfm_1_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sa_engine_ip_v1_0_bfm_1_master_0_0 || ORIG_REF_NAME==sa_engine_ip_v1_0_bfm_1_master_0_0} -quiet] -quiet

# IP: bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_sa_engine_ip_0_0/sa_engine_ip_v1_0_bfm_1_sa_engine_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sa_engine_ip_v1_0_bfm_1_sa_engine_ip_0_0 || ORIG_REF_NAME==sa_engine_ip_v1_0_bfm_1_sa_engine_ip_0_0} -quiet] -quiet

# XDC: c:/Users/User/Desktop/git/cau-capstone/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_vip_test.gen/sources_1/bd/sa_engine_ip_v1_0_bfm_1/sa_engine_ip_v1_0_bfm_1_ooc.xdc
