@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Oct 28 14:28:22 +0900 2025
=======
REM Generated by Vivado on Fri Oct 17 11:36:37 +0900 2025
>>>>>>> 5a1be21c592a9e5cddb782db4e28fd23eae160df
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
<<<<<<< HEAD
echo "xsim sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/se-dong Jang/종합설계/cau-capstone-systolic-array/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log"
call xsim  sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/se-dong Jang/종합설계/cau-capstone-systolic-array/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log
=======
echo "xsim sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/sudea/capstone_design_final/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log"
call xsim  sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/sudea/capstone_design_final/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log
>>>>>>> 5a1be21c592a9e5cddb782db4e28fd23eae160df
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
