@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Nov 02 01:03:00 +0900 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/se-dong Jang/종합설계/cau-capstone-systolic-array/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log"
call xsim  sa_engine_tb_behav -key {Behavioral:sim_1:Functional:sa_engine_tb} -tclbatch sa_engine_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/se-dong Jang/종합설계/cau-capstone-systolic-array/waveform_data/sa_engine_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
