# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_vip_test.srcs/sources_1/bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_master_0_0/sa_engine_ip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'sa_engine_ip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_vip_test.gen/sources_1/bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_master_0_0/sa_engine_ip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sa_engine_ip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_vip_test.srcs/sources_1/bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_master_0_0/sa_engine_ip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'sa_engine_ip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/sudea/capstone_design_final/sa_engine_ip_1.0/sim_projects/sa_vip_test/sa_vip_test.gen/sources_1/bd/sa_engine_ip_v1_0_bfm_1/ip/sa_engine_ip_v1_0_bfm_1_master_0_0/sa_engine_ip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sa_engine_ip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
