///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package sa_engine_ip_v1_0_bfm_1_slave_0_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_PROTOCOL           = 2;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_INTERFACE_MODE     = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ADDR_WIDTH         = 32;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_DATA_WIDTH         = 32;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ID_WIDTH           = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_AWUSER_WIDTH       = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ARUSER_WIDTH       = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_RUSER_WIDTH        = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_WUSER_WIDTH        = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_BUSER_WIDTH        = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_SUPPORTS_NARROW    = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_BURST          = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_LOCK           = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_CACHE          = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_REGION         = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_QOS            = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_PROT           = 1;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_WSTRB          = 1;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_BRESP          = 1;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_RRESP          = 1;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_ACLKEN         = 0;
      parameter sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi_mst_agent #(sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_PROTOCOL, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ADDR_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_DATA_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_DATA_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ID_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ID_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_AWUSER_WIDTH, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_WUSER_WIDTH, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_BUSER_WIDTH, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_ARUSER_WIDTH,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_RUSER_WIDTH, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_SUPPORTS_NARROW, 
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_BURST,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_LOCK,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_CACHE,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_REGION,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_PROT,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_QOS,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_WSTRB,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_BRESP,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_RRESP,
                        sa_engine_ip_v1_0_bfm_1_slave_0_0_VIP_HAS_ARESETN) sa_engine_ip_v1_0_bfm_1_slave_0_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      sa_engine_ip_v1_0_bfm_1_slave_0_0_mst_t  sa_engine_ip_v1_0_bfm_1_slave_0_0_mst;
//      initial begin : START_sa_engine_ip_v1_0_bfm_1_slave_0_0_MASTER
//        sa_engine_ip_v1_0_bfm_1_slave_0_0_mst = new("sa_engine_ip_v1_0_bfm_1_slave_0_0_mst", `sa_engine_ip_v1_0_bfm_1_slave_0_0_PATH_TO_INTERFACE);
//        sa_engine_ip_v1_0_bfm_1_slave_0_0_mst.start_master();
//      end



endpackage : sa_engine_ip_v1_0_bfm_1_slave_0_0_pkg
